{"intents": [
    {"tag": "greetings",
     "patterns": ["Hello", "Hey", "Hi"],
     "responses": ["What's up?", "How can I help you?", "Hi, I am at your service"],
     },
    {"tag": "farewell",
     "patterns": ["Bye", "See you later", "I do not need any more help"],
     "responses": ["Great, feel free to have another chat anytime you like!", "Bye Bye"],
     },
    {"tag": "hours",
     "patterns": ["What time do you close", "What days are you open", "What are the business hours?"],
     "responses": ["The Ardonagh Group is open Monday to Friday from 8am till 6pm, but you can chat to me 24/7"],
     },
    {"tag": "name",
     "patterns": ["What is your name?", "Do you have a name?"],
     "responses": ["My name is Janine", "I go by the name Janine", "You can call me Janine"],
     },
    {"tag": "role",
     "patterns": ["What is your role?", "What is your purpose?", "What can you do?"],
     "responses": ["I am an intelligent Chatbot that will answer all your Cyber Security Questions as well as bring you the latest Cyber attack news. I could also submit Security Incidents"],
     },
    {"tag": "funny",
     "patterns": ["Tell me a joke", "Tell me something funny", "Do you know any jokes"],
     "responses": ["There's a band called 1023MB. Ever heard of them? They haven't had a gig yet.",
                   "So, the other day I started to whisper and my wife asked why I was whispering? I told her I didn't want Mark Zuckerberg to hear us. I laughed. My wife laughed. Alexa laughed. Siri laughed.", "What do you call a group of math and science geeks at a party? Social engineers!", "99 little bugs in the code, 99 little bugs, Take one down, patch it around, 117 little bugs in the code.", "CAPS LOCK: Preventing Logins Since 1980", "If Bill Gates had a penny for every time I had to reboot my computer... oh wait, he does."],
     },
    {"tag": "news",
     "patterns": ["Breaking News", "What is the latest attack", "download latest Cyber attacks"],
     "responses": ["Latest Cyber News downloaded."],
     },
    {"tag": "incidents",
     "patterns": ["How can I submit an incident?", "I need to submit an incident",
                  "There was a security incident that took place"],
     "responses": ["It is important to provide use with accurate data, please follow the steps below"],
     },
    {"tag": "questions",
     "patterns": ["I have a question", "can I ask a question?", "Do you answer any questions?"],
     "responses": ["of course, what would you like to know?"],
     }
]}
